### PR TITLE
Lifecycle support for non-current versions

### LINKED ISSUE #15: Lifecycle support for non-current versions
The library is missing support to set expiration to non-current version via Bucket Lifecycle. 

More info about the lifecycle request and the expected XML encoding:

http://doc.isilon.com/ECS/3.1/API/S3BucketLifecycleOperation_getBucketLifeCycle_4c7f2e74398d6b6d0b799bd19ef9a5cc_ba672412ac371bb6cf4e69291344510e_detail.html

### PR DESCRIPTION
**Pull request by adrianmo**
Fixes #15

### CODE REVIEW

**Comment by adrianmo** [comment]
@twincitiesguy I haven't managed to make it work yet. I'm having issues with the XML marshalling when the non-current expiration is not set.

Currently, when non-current expiration is not set, the marshaller generates the following XML:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Rule>
        <ID>rule-a</ID>
        <Prefix>abc</Prefix>
        <Status>Enabled</Status>
        <Expiration>
            <Days>1</Days>
        </Expiration>
        <NoncurrentVersionExpiration/>
    </Rule>
</LifecycleConfiguration>```

The above content causes the request to fail because of "<NoncurrentVersionExpiration/>".

I'd like the marshaller to skip the non-current tag if it's not set.

The desired output would be the following:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Rule>
        <ID>rule-a</ID>
        <Prefix>abc</Prefix>
        <Status>Enabled</Status>
        <Expiration>
            <Days>1</Days>
        </Expiration>
    </Rule>
</LifecycleConfiguration>```

@twincitiesguy any ideas how to make this work?

**Comment by DavidASeibert** [comment]
@adrianmo You can allow elements to be skipped by adding the attributes `nillable=true, required=false` to the `@XmlElement` annotation. It’s pretty much impossible to get more fine-grained control, though. If you do that, you probably also need to fix all of the code that refers to that field so that it doesn’t blow up if the field is null.

**Comment by adrianmo** [comment]
@DavidASeibert your suggestion is producing the same results. But I think I found the cause and a solution to it. 

Looks like by default, if an element is skipped if it has "null" value, but the problem was that "NoncurrentVersionExpiration" was never "null" even if it was not set because it's a class.

```
    @XmlAccessorType(XmlAccessType.FIELD)
    protected static class NoncurrentVersionExpiration {
        @XmlElement(name = "NoncurrentDays")
        public Integer noncurrentDays;
    }
```
So I updated the getter like this to check the `noncurrentDays` attribute and return `null` if it's `null`.

```
    @XmlElement(name = "NoncurrentVersionExpiration")
    protected NoncurrentVersionExpiration getNoncurrentVersionExpiration() {
        if (noncurrentVersionExpiration.noncurrentDays == null) {
            return null;
        } else {
            return noncurrentVersionExpiration;
        }
    }
```
This is now producing the desired output and works fine with ECS.

Will submit the code in a moment.

**Comment by adrianmo** [comment]
@DavidASeibert @twincitiesguy can you please review?

**Comment by DavidASeibert** [comment]
@adrianmo I see the problem - I missed the fact that your default constructor instantiates a `NoncurrentVersionExpiration` object for the `noncurrentVersionExpiration` field. If you don't want it to be there, you should just leave it as null, and the rest of the code should handle it. That will let you get around those hacks where you return null when the object isn't null.

**Comment by adrianmo** [comment]
@DavidASeibert you are right. But then I should also handle the setters (`setExpirationDays`, `setExpirationDate`, `setNoncurrentDays`) and instantiate `NoncurrentVersionExpiration` and `Expiration` objects when their properties are set.

I think the current approach is a bit cleaner.

**Comment by adrianmo** [comment]
@DavidASeibert @twincitiesguy can you please review the new changes?

**Comment by adrianmo** [comment]
@twincitiesguy @DavidASeibert ping

**Comment by DavidASeibert** [comment]
Looks good to me except for the tests. Since the new `NoncurrentVersionExpiration` element is optional, you need tests both with and without it. From what I see, you have only tests with it now.

**Comment by adrianmo** [comment]
@DavidASeibert Thanks for the feedback. I've just added a few more test rules following your recommendation.

**Comment by twincitiesguy** [comment]
Looks good to me, but can you please add a regression test to `LifecycleConfigurationTest` that tests the XML with all fields nulled?

**Comment by adrianmo** [comment]
@twincitiesguy done

**Pull request merged**
